version: "3.7"

services:
    laravel-api:
        container_name: laravel-api
        build:
            context: .docker/php
            dockerfile: Dockerfile
        ports:
            - 8088:8000
        volumes:
            - ./:/www
        tty: true
        restart: always
    laravel-redis:
        container_name: laravel-redis
        image: redis
        command: redis-server --requirepass root:root
        ports:
            - "6397:6379"
        restart: always
